[workspace]
resolver = "2"

members = [
    "dex_aggregator/common",
    "dex_aggregator/chain_metadata",
    "dex_aggregator/routing",
    "dex_aggregator/execution_plan",
    "dex_aggregator/executor",
]

